#!/usr/bin/env bash
# Generate docs/guides/CI_PARITY.md — compare fork vs upstream GitHub Actions.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

UPSTREAM="${UPSTREAM_REPO:-pewdiepie-archdaemon/odysseus}"
FORK="${FORK_REPO:-lawmight/odysseus}"
OUT="${1:-docs/guides/CI_PARITY.md}"
GENERATED_AT="$(date -u +"%Y-%m-%d %H:%M UTC")"

if ! command -v gh >/dev/null 2>&1; then
  echo "ci-parity-report: gh CLI required" >&2
  exit 1
fi

workflow_tree() {
  local repo="$1"
  gh api graphql -f query="
  {
    repository(owner:\"${repo%%/*}\", name:\"${repo##*/}\") {
      object(expression:\"main:.github/workflows/\") {
        ... on Tree { entries { name } }
      }
    }
  }" --jq '.data.repository.object.entries // [] | map(.name) | sort | .[]' 2>/dev/null || true
}

registered_workflows() {
  local repo="$1"
  gh api "repos/${repo}/actions/workflows" --jq '.workflows[] | select(.path | startswith(".github/")) | .path' 2>/dev/null | sort -u || true
}

issues_enabled() {
  local repo="$1"
  gh api "repos/${repo}" --jq '.has_issues' 2>/dev/null || echo "unknown"
}

mkdir -p "$(dirname "$OUT")"

{
  echo "# CI parity: fork vs upstream"
  echo ""
  echo "_Auto-generated by [\`scripts/ci-parity-report.sh\`](../../scripts/ci-parity-report.sh) at ${GENERATED_AT}. Re-run after upstream syncs CI workflows._"
  echo ""
  echo "| Repository | GitHub |"
  echo "|------------|--------|"
  echo "| Upstream | \`${UPSTREAM}\` |"
  echo "| Fork | \`${FORK}\` |"
  echo ""
  echo "## Workflow files on \`main\` (source of truth)"
  echo ""
  echo "GraphQL tree for \`.github/workflows/\` — only files present on the default branch count for merge gates."
  echo ""
  echo "### Upstream"
  echo ""
  up_tree="$(workflow_tree "$UPSTREAM")"
  if [[ -z "$up_tree" ]]; then
    echo "_none or unavailable_"
  else
    while IFS= read -r f; do echo "- \`${f}\`"; done <<< "$up_tree"
  fi
  echo ""
  echo "### Fork"
  echo ""
  fork_tree="$(workflow_tree "$FORK")"
  if [[ -z "$fork_tree" ]]; then
    echo "_none or unavailable_"
  else
    while IFS= read -r f; do echo "- \`${f}\`"; done <<< "$fork_tree"
  fi
  echo ""
  echo "## Registered Actions workflows (may include stale entries)"
  echo ""
  echo "The Actions API can list workflows that no longer exist on \`main\`. Prefer the tree above when syncing."
  echo ""
  echo "### Upstream (registered)"
  echo ""
  up_reg="$(registered_workflows "$UPSTREAM")"
  if [[ -z "$up_reg" ]]; then
    echo "_none_"
  else
    while IFS= read -r f; do echo "- \`${f}\`"; done <<< "$up_reg"
  fi
  echo ""
  echo "### Fork (registered)"
  echo ""
  fork_reg="$(registered_workflows "$FORK")"
  if [[ -z "$fork_reg" ]]; then
    echo "_none_"
  else
    while IFS= read -r f; do echo "- \`${f}\`"; done <<< "$fork_reg"
  fi
  echo ""
  echo "## Gate mapping"
  echo ""
  echo "| Gate | Upstream \`main\` | Fork \`main\` | Fork covers upstream? |"
  echo "|------|-----------------|-------------|------------------------|"
  echo "| PR description bot | \`pr-description-check.yml\` | same file (shared script) | yes |"
  echo "| Issue description bot | \`issue-description-check.yml\` | same file; fork issues **$(issues_enabled "$FORK")** | N/A on fork if issues off |"
  echo "| Full \`pytest\` | manual per CONTRIBUTING | \`ci.yml\` → \`test\` | yes (stricter) |"
  echo "| Python/JS syntax | manual | \`ci.yml\` → \`syntax\` | yes |"
  echo "| Secret scan | manual | \`ci.yml\` → \`secrets\` | yes |"
  echo "| Docker compose config | manual | \`docker.yml\` → \`docker-config\` | yes |"
  echo "| Docker image build | manual | \`docker.yml\` → \`docker-build\` | yes |"
  echo ""
  echo "**Implication:** Green CI on the fork is a superset of upstream’s automated expectations on \`main\` today. Upstream PRs still require a complete PR description and (for agents) issue-first workflow on \`${UPSTREAM}\`."
  echo ""
  echo "## Fork branch protection (documented)"
  echo ""
  echo "From [CONTRIBUTING.md](../../CONTRIBUTING.md): required checks on \`${FORK}\` \`main\` PRs:"
  echo ""
  echo "- \`test\`"
  echo "- \`syntax\`"
  echo "- \`secrets\`"
  echo "- \`docker-config\`"
  echo "- \`docker-build\`"
  echo "- \`Check PR description\` (workflow name: \`ci / PR description check\`)"
  echo ""
  echo "## Sync policy"
  echo ""
  echo "1. Re-run \`bash scripts/ci-parity-report.sh\` after merging upstream \`main\`."
  echo "2. If upstream adds new workflow files to \`main\`, port them in a focused \`chore: sync upstream CI\` PR."
  echo "3. Do **not** copy workflows that appear only in the Actions API but not in upstream’s \`main\` tree (likely stale)."
  echo ""
  echo "## Local preflight"
  echo ""
  echo "Run \`bash scripts/ci-preflight.sh\` before pushing. See [UPSTREAM_PR_GUIDELINES.md](./UPSTREAM_PR_GUIDELINES.md)."
} > "$OUT"

echo "Wrote ${OUT}"
